[package]
org = "wso2"
name = "sarcastic_bot"
version = "0.1.0"
distribution = "2201.9.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "openai.finetunes"
version = "1.0.7"
repository = "local"
